### ISSUE TITLE
App service email plugin support for HTML content

### ISSUE THREAD

**Issue by AndreLees** [Azure/Wordpress-on-Linux-App-Service-plugins#18]
https://github.com/Azure/Wordpress-on-Linux-App-Service-plugins/blob/22c7be117d868a5226f794b568786ce62d76c1de/app_service_email/admin/mailer/class-azure_app_service_email-controller.php#L89C23-L89C23

Can we update the mail class to support html content?
HTML forms in Wordpress get emailed out as raw text with html tags, which is not pretty!

**Comment by rabollin** [comment]
Good feedback @AndreLees ; will fix it as a priority.

**Comment by bmanjwani** [comment]
Thanks for pointing this out @AndreLees , Can you help us with the steps to replicate the scenario?

**Comment by AndreLees** [comment]
No problem @bmanjwani, glad to help :)

I discovered this with a Gravity Forms Survey.
If you add a Notification to the Survey Form Settings and add a merge tag to the body "{all fields}" it will generate html tags around the survey fields to make them pretty. 

![image](https://github.com/Azure/Wordpress-on-Linux-App-Service-plugins/assets/142796263/25418e06-016f-4c12-9836-0df2efce4182)

However, the "generate_request_body" function uses 'plaintext' as the content parameter and the resulting email shows raw html tags.

![image](https://github.com/Azure/Wordpress-on-Linux-App-Service-plugins/assets/142796263/75d231b5-7775-4ebe-a639-a082645eeaef)

This is the resulting email:

![image](https://github.com/Azure/Wordpress-on-Linux-App-Service-plugins/assets/142796263/82c11af3-8387-4edf-99d9-daf65d638de5)

Easy enough to fix by changing the parameter to 'html'

**Comment by bmanjwani** [comment]
@AndreLees , Replacing plaintext with html is disturbing the formatting of standard wordpress emails like password reset email, user registeration email etc. 
We are working to resolve this issue and will have it fixed soon.
TIA

**Comment by bmanjwani** [comment]
@AndreLees , we have updated the plugin code in this repo. It would be great if you can check and confirm if the fix is working fine for you.
TIA

**Comment by Mark-Colquhoun** [comment]
Hi,

I'm having the same problem with Avada Forms. I was hoping to install the latest version after the change but I can't find the zip file even though the action says it has completed. Are you able to give me a hand by letting me know how I can install the latest update?

Thanks,
Mark.

**Comment by bmanjwani** [comment]
@Mark-Colquhoun Please use this [link](https://download-directory.github.io/?url=https%3A%2F%2Fgithub.com%2FAzure%2FWordpress-on-Linux-App-Service-plugins%2Ftree%2Fmain%2Fapp_service_email) to download the zip file of latest plugin code.
Please let us know if this works for you.

**Comment by AndreLees** [comment]
@bmanjwani have tested out your updated code and seems to be working well.
The form notification is nicely formatted in html and the WordPress user activation emails show in the existing boring old plaintext :-)

**Comment by Mark-Colquhoun** [comment]
@bmanjwani, yep that fixed my problem. Thanks for working on the plugin and also, thanks for the quick response.

**Comment by bmanjwani** [comment]
@AndreLees and @Mark-Colquhoun Thanks for confirming.
Closing the issue as it has been fixed.
